### ISSUE TITLE
请问有没什么办法能兼容哔嘀的那个分类的fypage问题

### ISSUE THREAD

**Issue by xiaoxiao2020** [hjdhnx/hipy-server#10]
/s/all/2?type=0 电影 
/s/all/2?type=1 电视剧
/s/meiju/2  美剧
/s/gangtaiju/2 港台 

2 是    fypage

type  是分类
all  meiju gangtaiju  是类型
类型是 meiju gangtaiju 这种的时候 type=空
但是电影 和 电视剧 type 是0和1
这就导致了  fypage 无法兼容

url:'/s/fyfilter[/s/all/fypage?type=fyclass]',
filter_url:'{{fl.lx}}/fypage?type=fyclass&{{fl.area}}&{{fl.year}}&{{fl.by}}',
    class_name: '电影&电视剧',
    class_url: '0&1',
这样也没法兼容

**Comment by hjdhnx** [comment]
没法，只能手动传类型和page，一级写js去判断然后拼接链接。
