### ISSUE TITLE
大佬  tab_remove 线路过滤 里面能加入正则过滤吗

### ISSUE THREAD

**Issue by xiaoxiao2020** [hjdhnx/hipy-server#12]
网页源码
<div class="playlists" id="slider">
<header>
    <dl>
        <dt class="on">海外专线<small><span style="position:absolute;transform: scale(.8);transform-origin: top right;font-weight: 400;background-color: #0ae;color: #FFF;padding: 0 5px 0 5px;border-radius: 0 5px 0 5px;height: 19px;line-height: 20px;font-size: 8px;">10</span></small></dt>
        <dt class="">高清资源<small><span style="position:absolute;transform: scale(.8);transform-origin: top right;font-weight: 400;background-color: #0ae;color: #FFF;padding: 0 5px 0 5px;border-radius: 0 5px 0 5px;height: 19px;line-height: 20px;font-size: 8px;">10</span></small></dt>
    </dl>
</header>
</div>

tabs 获取
"tabs": "#slider dt",

获取到的tabs
比如 有些线路 获取tabs的时候 会一并获取到线路名和数字，数字是会变动的过滤无法长久有效 tab_remove:['海外专线10'], 这种就没什么用了
比如 海外专线12 高清资源10 乐视资源12 飞速资源11  这种 ，tab_remove过滤线路又不能模糊过滤

能不能对 tab_remove 进行一下改进 能正则过滤 或者 模糊过滤  达到下面的效果
tab_remove:['海外专线\\d+'],
tab_remove:['海外'],  
或者还能有更好的方法获取到tabs
JS代码实在是不懂

**Comment by hjdhnx** [comment]
数字这种，你就是tab_text定位错了。用--过滤数字

**Comment by xiaoxiao2020** [comment]
谢了，知道怎么搞了 #slider dt--small 这样就没数字了
