### ISSUE TITLE
请教该项目相对于dr_py有什么区别

### ISSUE THREAD

**Issue by 9E307** [hjdhnx/hipy-server#6]
如题，不理解两个项目之间的差异和优劣点，另外以后[dr_py](https://github.com/hjdhnx/dr_py)是否会停止更新，全面转入hipy到这里来？

**Comment by hjdhnx** [comment]
是的dr_py项目基本已经停更。以后专门维护hipy项目。hipy项目可以看做drpy项目的全方面升级，更好的兼容js源。同时支持js/py源的t3/t4服务

**Comment by 9E307** [comment]
那么，部署方式依然和部署drpy一样么，我部署drpy是全自动化处理的，并且用的是docker，目前搜了下没有啥部署hipy的教程。

hjdhnx ***@***.***> 于2024年5月7日周二 12:40写道：

**Comment by hjdhnx** [comment]
https://zy.catni.cn/hipy-build.html 这是搭建教程
