### ISSUE TITLE
最新drpy2不知道是不是有bug

### ISSUE THREAD

**Issue by jak0099** [hjdhnx/hipy-server#7]
视频测试播放器EasyBox_139，本地源模式下，最新drpy2,无法识别站源，若用内置drpy2模式或在github仓库模式下，又都可以正常识别站源读取数据，另外用ok&fm影视也都这种情况

https://github.com/hjdhnx/hipy-server/assets/90884864/845e23f3-4b8a-4a11-a007-6a99b5263b3b

**Comment by hjdhnx** [comment]
不存在这种问题。除非你本地的drpy2涉及的所有libs你自己没对应放到本地

**Comment by jak0099** [comment]
可能是一个小概率的事件，我同步在github仓库下源的是能正常读取源数据的，都是用相对路径的，影视，EasyBox本地就是读不了站源数据，然后我用catbox,影视仓又测试了一遍，本地站源数据可以正常读取的；没事，我换个播放器就可以了，只想着这可能是有个小bug存在，报告一下

**Comment by jak0099** [comment]
可能找到问题所在了，将模板回滚到一个旧点的板本，所有播放器都可以正常在本地拉取站源数据了

**Comment by hjdhnx** [comment]
你的意思是模板.js里的问题吗

**Comment by hjdhnx** [comment]
好了，知道了，模板.js有问题，我一会儿修复，感谢反馈
