### ISSUE TITLE
请问看了网站源代码基本一样模板套用用不了是什么情况

### ISSUE THREAD

**Issue by xiaoxiao2020** [hjdhnx/hipy-server#8]
92kyy.com和aikanhd.vip 网站几乎一样mxpro模板用不了

**Comment by xiaoxiao2020** [comment]
class_parse: '.navbar-items li:gt(0):lt(8);a&&Text;a&&href;.*/(\\d+)',
href 后面的正则明明测试是对的但是放到源里面测试死活获取不到,用 .*/(.*?) 这个也不行

**Comment by xiaoxiao2020** [comment]
然后发现 href 如果是 /type/dianying/ 这种 ，/vodtype/1/ 这种的 都不行 href 死活不行，分类获取不了

**Comment by hjdhnx** [comment]
字符串里写正则 (\\d+) 另外 /type/dianying/  这种，只需要 .*/(.*?)/

**Comment by hjdhnx** [comment]
![image](https://github.com/hjdhnx/hipy-server/assets/49803097/f2c0c717-bfa6-4ec9-a187-db2744d89d59)
这个网站获取源码有验证，由于获取不到正确的源码所以套不了

**Comment by hjdhnx** [comment]
![image](https://github.com/hjdhnx/hipy-server/assets/49803097/4e5f52b5-c6ff-417c-8531-3af6188b3d25)
第一个站正常

**Comment by hjdhnx** [comment]
第二个站是UA问题
```javascript
Object.assign(muban.mxpro.二级, {
    tab_text: 'div--small&&Text',
});
var rule = {
    模板: 'mxpro',
    title: '爱看hd',
    host: 'https://www.aikanhd.vip/',
    headers: {'User-Agent': IOS_UA},
    class_parse: '.navbar-items li:gt(0):lt(10);a&&Text;a&&href;.*/(\\d+)',
    cate_exclude: '今日更新|排序',
    url: '/vodshow/fyclass--------fypage---.html',
    searchUrl: '/vodsearch/**----------fypage---/',
    tab_exclude: '排序',
}
```

**Comment by xiaoxiao2020** [comment]
谢谢百忙之中解答，非常感谢
